services:
  postgres-backend:
    container_name: postgres-backend 
    build:
      context: .
      dockerfile: postgres/backend/Dockerfile
    secrets:
      - BACKEND_POSTGRES_USER
      - BACKEND_POSTGRES_PASSWORD
      - BACKEND_POSTGRES_DB
    volumes:
      - backend_postgres_data:${PG_MOUNT}/data
      - pg-certs-backend-server:${PG_MOUNT}/certs:ro
    networks:
      - internal-net
    restart: unless-stopped

  postgres-mlflow:
    container_name: postgres-mlflow
    build:
      context: .
      dockerfile: postgres/mlflow/Dockerfile
    secrets:
      - MLFLOW_POSTGRES_USER
      - MLFLOW_POSTGRES_PASSWORD
      - MLFLOW_POSTGRES_DB
    volumes:
      - mlflow_postgres_data:${PG_MOUNT}/data
      - pg-certs-mlflow-server:${PG_MOUNT}/certs:ro
    networks:
      - internal-net
    restart: unless-stopped
    
  pgadmin:
    build:
      context: .
      dockerfile: pgadmin/Dockerfile
    secrets:
      - PGADMIN_EMAIL
      - PGADMIN_PASSWORD
      - PGADMIN_EMAIL_PATH
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pg-certs-backend-pgadmin:/var/lib/pgadmin/storage/${PGADMIN_EMAIL_PATH}/certs/backend
      - pg-certs-mlflow-pgadmin:/var/lib/pgadmin/storage/${PGADMIN_EMAIL_PATH}/certs/mlflow
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.nxfive.pl`)"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-ipwhitelist@docker"
      - "traefik.http.middlewares.pgadmin-ipwhitelist.ipwhitelist.sourcerange=10.200.200.0/24"
    networks:
      - traefik-net
      - internal-net
    restart: unless-stopped

  mlflow:
    image: ghcr.io/nxfive/ml-medical-cost/mlflow:latest
    secrets:
      - MLFLOW_POSTGRES_USER
      - MLFLOW_POSTGRES_PASSWORD
      - MLFLOW_POSTGRES_DB
      - POSTGRES_PORT
      - MLFLOW_HOST
    environment:
      POSTGRES_SERVICE: postgres-mlflow
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
      - pg-certs-mlflow-client:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.mlflow.rule=Host(`mlflow.nxfive.pl`)"
      - "traefik.http.routers.mlflow.tls=true"
      - "traefik.http.routers.mlflow.service=mlflow"
      - "traefik.http.services.mlflow.loadbalancer.server.port=5000"
      - "traefik.http.routers.mlflow.middlewares=mlflow-ipwhitelist@docker"
      - "traefik.http.middlewares.mlflow-ipwhitelist.ipwhitelist.sourcerange=10.200.200.0/24"
    networks:
      - traefik-net
      - internal-net
    restart: unless-stopped


volumes:
  backend_postgres_data:
  mlflow_postgres_data:
  pgadmin_data:

  pg-certs-backend-server:
    external: true
    name: config_pg-certs-backend-server
  pg-certs-backend-client:
    external: true
    name: config_pg-certs-backend-client
  pg-certs-backend-pgadmin:
    external: true
    name: config_pg-certs-backend-pgadmin

  pg-certs-mlflow-server:
    external: true
    name: config_pg-certs-mlflow-server
  pg-certs-mlflow-client:
    external: true
    name: config_pg-certs-mlflow-client
  pg-certs-mlflow-pgadmin:
    external: true
    name: config_pg-certs-mlflow-pgadmin


networks:
  traefik-net:
    external: true
  internal-net:
    external: true


secrets:
  BACKEND_POSTGRES_USER:
    external: true 
  BACKEND_POSTGRES_PASSWORD:
    external: true
  BACKEND_POSTGRES_DB:
    external: true

  MLFLOW_POSTGRES_USER:
    external: true
  MLFLOW_POSTGRES_PASSWORD:
    external: true
  MLFLOW_POSTGRES_DB:
    external: true

  PGADMIN_EMAIL:
    external: true
  PGADMIN_PASSWORD:
    external: true
  PGADMIN_EMAIL_PATH:
    external: true