defaults:
  - _self_
  - features: default
  - model: linear
  - cv: default
  - transform: default
  - optuna: linear

project_name: ml-medical-cost

stage: training

data:
  root_dir: "data"
  raw_dir: "${data.root_dir}/raw"
  processed_dir: "${data.root_dir}/processed"

training:
  output_dir: "src/training/results"
  model_file: "pipeline.pkl"
  metrics_file: "metrics.yaml"

models:
  output_dir: "models"

kaggle:
  handle: mirichoi0218/insurance
  filename: insurance.csv